[package]
name = "init-keys"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
secp256k1 = { version = "0.29", features = ["global-context", "rand-std", "recovery"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ethers = "2.0.14"
base64 = "0.21"
hex = "0.4"

